version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "06:00"
  open-pull-requests-limit: 99
  reviewers:
  - danirod
  assignees:
  - danirod
  labels:
  - dependencies
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: bundler
    versions:
    - 2.2.0
